### ISSUE TITLE
Issue with pulling framerate from VideoIO object

### ISSUE THREAD

**Issue by dcschaper** [oschulz/julia-course#8]
It seems like the line in the julia-course-example.ipynb notebook that tries to pull the framerate from the video has an issue with how it is trying to access this field (I can't reference the specific line in the code here due to it being a .ipynb file). 

The line:
fps = VideoIO.framerate(video_input)/1000 * u"s^-1"

Throws the error:
"type VideoReader has no field framerate"

However, if I change it to call:

fps = VideoIO.framerate(video_input)/1000 * u"s^-1"

It seems to work.

This seems to be related to this discussion that I found here on a JuliaIO issue (https://github.com/JuliaIO/VideoIO.jl/issues/349)

**Comment by oschulz** [comment]
Thanks, should be fixed now.
