### ISSUE TITLE
Example notebook needs a 'using Plots' statement

### ISSUE THREAD

**Issue by dcschaper** [oschulz/julia-course#9]
The cell that plots the different frames from the video does not run because there is no call to 'using Plots' in the notebook until the next cell after the initial plot() command is called. I added it in the same cell that the plotting functionality is called in, namely:

------------
using Plots

plot(plot.(broadcast(
    (input, t) -> read_frame(input, t)[1:5:end,1:5:end]',
    Ref(video_input),
    0u"s":1u"s":video_duration
), axis=nothing)...)

------------

**Comment by oschulz** [comment]
Thanks, should be fixed now.
